---
# defaults file for gcp_ocp_deployment

## GCP account / project specific variables.

# These shouldn't be populated here, rather they are documented
# here as a template for further playbooks.

# This is based on the Ansible GCP documentation here
# https://docs.ansible.com/ansible/latest/scenario_guides/guide_gce.html

# The project-id of the GCP project we intend to work on.
gcp_project_id: "openenv-k974t"

# The project-name of the GCP project above
gcp_project_name: "openenv-k974t"

# GCP organisation ID is established with the following command
# "gcloud projects describe [project-id]"
# e.g. "gcloud projects describe rhpds-345620 | grep -1 parent"
# For some tasks, on some accounts we are required to specify
gcp_organization_id: 54643501348

# What kind of account will we be working with ?
gcp_cred_kind: serviceaccount

# The JSON dump of the account credentials.
# gcp_cred_file: "/home/my_account.json"
## Currently set to be my test credentials
gcp_cred_file: "/home/myork/.config/gcloud/application_default_credentials.json"

# Default zones and regions
zone: "us-central1-a"
region: "us-central1"
